
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMENT DELIMETER FLAG FLAG_DEF IMMEDIATE NO_REG_INSTRUCTION ONE_REG_INSTRUCTION REGISTER REG_DELIMETER TWO_REG_INSTRUCTION\n    parse : expression\n          | expression DELIMETER\n          | expression COMMENT DELIMETER\n          | expression COMMENT\n          | COMMENT DELIMETER\n          | COMMENT\n          | DELIMETER\n          | flag COMMENT DELIMETER\n          | flag COMMENT\n          | flag DELIMETER\n          | empty\n    \n    expression : NO_REG_INSTRUCTION\n               | ONE_REG_INSTRUCTION REGISTER\n               | ONE_REG_INSTRUCTION FLAG\n               | TWO_REG_INSTRUCTION REGISTER REG_DELIMETER REGISTER\n               | TWO_REG_INSTRUCTION REGISTER REG_DELIMETER IMMEDIATE \n    \n    flag : FLAG_DEF\n    \n    empty : \n    '
    
_lr_action_items = {'COMMENT':([0,2,5,7,10,16,17,22,23,],[4,12,14,-12,-17,-13,-14,-15,-16,]),'DELIMETER':([0,2,4,5,7,10,12,14,16,17,22,23,],[3,11,13,15,-12,-17,19,20,-13,-14,-15,-16,]),'NO_REG_INSTRUCTION':([0,],[7,]),'ONE_REG_INSTRUCTION':([0,],[8,]),'TWO_REG_INSTRUCTION':([0,],[9,]),'FLAG_DEF':([0,],[10,]),'$end':([0,1,2,3,4,6,7,11,12,13,14,15,16,17,19,20,22,23,],[-18,0,-1,-7,-6,-11,-12,-2,-4,-5,-9,-10,-13,-14,-3,-8,-15,-16,]),'REGISTER':([8,9,21,],[16,18,22,]),'FLAG':([8,],[17,]),'REG_DELIMETER':([18,],[21,]),'IMMEDIATE':([21,],[23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'parse':([0,],[1,]),'expression':([0,],[2,]),'flag':([0,],[5,]),'empty':([0,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> parse","S'",1,None,None,None),
  ('parse -> expression','parse',1,'p_parse','parse.py',8),
  ('parse -> expression DELIMETER','parse',2,'p_parse','parse.py',9),
  ('parse -> expression COMMENT DELIMETER','parse',3,'p_parse','parse.py',10),
  ('parse -> expression COMMENT','parse',2,'p_parse','parse.py',11),
  ('parse -> COMMENT DELIMETER','parse',2,'p_parse','parse.py',12),
  ('parse -> COMMENT','parse',1,'p_parse','parse.py',13),
  ('parse -> DELIMETER','parse',1,'p_parse','parse.py',14),
  ('parse -> flag COMMENT DELIMETER','parse',3,'p_parse','parse.py',15),
  ('parse -> flag COMMENT','parse',2,'p_parse','parse.py',16),
  ('parse -> flag DELIMETER','parse',2,'p_parse','parse.py',17),
  ('parse -> empty','parse',1,'p_parse','parse.py',18),
  ('expression -> NO_REG_INSTRUCTION','expression',1,'p_expression','parse.py',25),
  ('expression -> ONE_REG_INSTRUCTION REGISTER','expression',2,'p_expression','parse.py',26),
  ('expression -> ONE_REG_INSTRUCTION FLAG','expression',2,'p_expression','parse.py',27),
  ('expression -> TWO_REG_INSTRUCTION REGISTER REG_DELIMETER REGISTER','expression',4,'p_expression','parse.py',28),
  ('expression -> TWO_REG_INSTRUCTION REGISTER REG_DELIMETER IMMEDIATE','expression',4,'p_expression','parse.py',29),
  ('flag -> FLAG_DEF','flag',1,'p_flag','parse.py',38),
  ('empty -> <empty>','empty',0,'p_empty','parse.py',44),
]
